# GitHub Action to build a YIO Remote web configurator for the YIO remote-os.
# Creates a pre-release if pushed on master branch without a version tag.
# Creates a release if pushed on master branch with a version tag.
---
  name: "Build & Release"

  on:
    push:
    pull_request:

  env:
    HASH_FILENAME: yio-web-configurator.hash

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            # History of 500 should be more than enough to calculate commit count since last release tag.
            fetch-depth: 500

        - name: Fetch all tags to determine version
          run: |
            git fetch origin +refs/tags/*:refs/tags/*
            echo "VERSION=$(git describe --match "v[0-9]*" --tags HEAD --always)" >> $GITHUB_ENV

        - name: Set build timestamp
          run: |
            echo "TIMESTAMP=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV

        - name: npm install, build
          run: |
            npm install
            npm run build
            
        - name: add version
          run: |
            cd dist
            echo ${{ env.VERSION }} > version.txt
 
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: YIO-web-configurator
            path: dist
            
    release:
      name: Create Release
      if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags/v')
      runs-on: ubuntu-latest
      needs: build

      steps:
        - run: mkdir release
        - name: Download release artifact
          uses: actions/download-artifact@v2
          with:
            name: YIO-web-configurator
            path: ./dist
       
        - name: Get artifact version
          run: |
            read -r APP_VERSION < dist/version.txt
            echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
            echo "TIMESTAMP=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
            
        - name: Create GitHub release archive
          run: |
            cd dist
            zip -r ../YIO-web-configurator-${{ env.APP_VERSION }}.zip .
            cd ..
            for filename in *.zip; do echo "sha256  `sha256sum $filename`" >> ${{ env.HASH_FILENAME }}; done;
            
        - name: Create Pre-Release ${{ env.VERSION }}
          uses: "marvinpinto/action-automatic-releases@latest"
          if: "!contains(github.ref, 'tags/v')"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build ${{ env.APP_VERSION }}"
            files: |
                *.zip
                ${{ env.HASH_FILENAME }}
                
        - name: Create Release ${{ env.VERSION }}
          uses: "marvinpinto/action-automatic-releases@latest"
          if: "contains(github.ref, 'tags/v')"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
                *.zip
                ${{ env.HASH_FILENAME }}
