# GitHub Action to build a YIO Remote web configurator for the YIO remote-os.
# Creates a pre-release if pushed on master branch without a version tag.
# Creates a release if pushed on master branch with a version tag.
---
  name: "Build & Release"

  on:
    push:
    pull_request:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Fetch all tags to determine version
          run: |
            git fetch origin +refs/tags/*:refs/tags/*
            echo "::set-env name=VERSION::$(git describe --match "v[0-9]*" --tags HEAD --always)"

        - name: Set build timestamp
          run: echo "::set-env name=TIMESTAMP::$(date +"%Y%m%d_%H%M%S")"      

        - name: npm install, build
          run: |
            npm install
            npm run build

        - name: Archive production artifacts
          uses: actions/upload-artifact@v1
          with:
            name: YIO Web configurator-${{env.VERSION}}
            path: dist
      
