# GitHub Action to build a YIO Remote web configurator for the YIO remote-os.
# Creates a pre-release if pushed on master branch without a version tag.
# Creates a release if pushed on master branch with a version tag.
---
  name: "Build & Release"

  on:
    push:
    pull_request:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: github env vars
          run: |
            echo "$GITHUB_REF"
            echo "$GITHUB_HEAD_REF"
            echo "$GITHUB_BASE_REF"

        - name: Checkout ${{ env.PROJECT_NAME}}
          uses: actions/checkout@v2
          with:
            # History of 500 should be more than enough to calculate commit count since last release tag.
            fetch-depth: 500
            path: ${{ env.PROJECT_NAME}}

        - name: Fetch all tags to determine version
          run: |
            cd ${{ env.PROJECT_NAME}}
            git fetch origin +refs/tags/*:refs/tags/*
            git describe --match "v[0-9]*" --tags HEAD --always

        - name: Set build timestamp
          run: echo "::set-env name=TIMESTAMP::$(date +"%Y%m%d_%H%M%S")"      

        - name: npm install, build
          run: |
            npm install
            npm run build

        - name: Archive production artifacts
          uses: actions/upload-artifact@v1
          with:
            name: ${{ env.APP_NAME }}
            path: dist
